targets:
  $default:
    builders:
      moor_generator:
        options:
          generate_connect_constructor: true
          data_class_to_companions: false
          skip_verification_code: true
          generate_values_in_copy_with: true